-- Files
require("lazy-config.plugin-config.treesitter")
require("lazy-config.plugin-config.color-scheme")
require("lazy-config.plugin-config.comment-box")
require("lazy-config.plugin-config.nvim-comment")
require("lazy-config.plugin-config.completions")
require("lazy-config.plugin-config.lsp-config")
require("lazy-config.plugin-config.telescope")
require("lazy-config.plugin-config.live-server")
require("lazy-config.plugin-config.file-explorer")
require("lazy-config.plugin-config.harpoon")
require("lazy-config.plugin-config.marks-nvim")
require("lazy-config.plugin-config.alpha-nvim")
-- require("lazy-config.plugin-config.indent-lines")
