require("plugin-config.lazy")
require("plugin-config.treesitter")
require("plugin-config.lsp")
require("plugin-config.neotree")
require("plugin-config.lualine")
require("plugin-config.completions")
require("plugin-config.auto-close")
require("plugin-config.emmet")
